"""Generate nextnano++ input decks from a template + a sweep config.

Home-laptop tool. Pure text substitution -- no nextnano, no license, no
solver -- so it runs anywhere and is **deterministic**: the same sweep YAML
always produces byte-identical decks (no timestamps, sorted ordering).

    python nextnano/scripts/generate_inputs.py --config nextnano/config/sweeps/example_sweep.yaml
    python nextnano/scripts/generate_inputs.py --config <sweep.yaml> --dry-run

Template placeholders use ``{{name}}`` (double braces) so they never collide
with nextnano's own single-brace blocks (``global{ ... }``) or ``$variables``.

Sweep YAML schema (paths are relative to the nextnano/ root):

    template: inputs/templates/qw_composition_sweep_template.in
    model_name: qw_composition_sweep
    output_subdir: inputs/03_parameter_sweeps
    constants:            # optional; applied to every deck
      temperature: 300
    grid:                 # optional; cartesian product -> one deck each
      al_fraction: [0.20, 0.30, 0.40]

Decks are written to  <output_subdir>/<model_name>/  as tracked text files.
"""

from __future__ import annotations

import argparse
import re
import sys
from itertools import product
from pathlib import Path

import yaml

from nn_config import NEXTNANO_ROOT

_PLACEHOLDER = re.compile(r"{{\s*(\w+)\s*}}")


class GenerateError(Exception):
    """Raised for any problem loading a sweep or rendering a template."""


def _fmt(value) -> str:
    """Render a parameter value deterministically for a deck / filename."""
    if isinstance(value, bool):  # avoid Python's True/False leaking in
        return "yes" if value else "no"
    return str(value)


def load_sweep(sweep_path: Path) -> dict:
    """Load and minimally validate a sweep YAML."""
    sweep_path = Path(sweep_path)
    if not sweep_path.is_file():
        raise GenerateError(f"sweep config not found: {sweep_path}")
    try:
        data = yaml.safe_load(sweep_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise GenerateError(f"{sweep_path} is not valid YAML: {exc}") from exc

    for key in ("template", "model_name", "output_subdir"):
        if not str(data.get(key, "") or "").strip():
            raise GenerateError(f"{sweep_path}: missing required key '{key}'.")

    grid = data.get("grid") or {}
    if grid and not isinstance(grid, dict):
        raise GenerateError(f"{sweep_path}: 'grid' must be a mapping of name -> list.")
    for name, values in grid.items():
        if not isinstance(values, list) or not values:
            raise GenerateError(
                f"{sweep_path}: grid entry '{name}' must be a non-empty list."
            )

    constants = data.get("constants") or {}
    if constants and not isinstance(constants, dict):
        raise GenerateError(f"{sweep_path}: 'constants' must be a mapping.")
    return data


def expand_grid(sweep: dict) -> list[dict]:
    """Cartesian product of the grid, deterministic (keys sorted)."""
    grid = sweep.get("grid") or {}
    keys = sorted(grid)
    if not keys:
        return [{}]  # constants-only: a single deck
    return [dict(zip(keys, combo)) for combo in product(*(grid[k] for k in keys))]


def render(text: str, params: dict, template_name: str = "<template>") -> str:
    """Substitute {{name}} placeholders; error on any left undefined."""
    missing: set[str] = set()

    def _sub(match: re.Match) -> str:
        key = match.group(1)
        if key not in params:
            missing.add(key)
            return match.group(0)
        return _fmt(params[key])

    out = _PLACEHOLDER.sub(_sub, text)
    if missing:
        raise GenerateError(
            f"template {template_name} references undefined placeholder(s): "
            f"{', '.join(sorted(missing))}. Add them to 'constants' or 'grid'."
        )
    return out


def _deck_name(index: int, combo: dict) -> str:
    """Deterministic filename: 01_key-val_key-val.in (grid keys sorted)."""
    parts = [f"{k}-{_fmt(combo[k])}" for k in sorted(combo)]
    stem = "_".join(parts) if parts else "baseline"
    return f"{index:02d}_{stem}.in"


def _header(template_rel: str, params: dict) -> str:
    pretty = ", ".join(f"{k}={_fmt(params[k])}" for k in sorted(params))
    return (
        "# ---------------------------------------------------------------------------\n"
        "# GENERATED by nextnano/scripts/generate_inputs.py -- DO NOT EDIT BY HAND.\n"
        f"# template : {template_rel}\n"
        f"# params   : {pretty}\n"
        "# Edit the template + sweep config and regenerate.\n"
        "# ---------------------------------------------------------------------------\n"
    )


def generate(
    sweep_path: Path,
    *,
    output_root: Path | None = None,
    dry_run: bool = False,
) -> list[tuple[Path, dict]]:
    """Generate all decks for a sweep. Returns [(deck_path, params), ...].

    ``output_root`` overrides where decks are written (defaults to the repo's
    nextnano/ root); the template is always resolved under the repo. Files are
    written with LF newlines so output is identical across platforms.
    """
    sweep = load_sweep(sweep_path)
    template_rel = str(sweep["template"]).strip()
    template_path = NEXTNANO_ROOT / template_rel
    if not template_path.is_file():
        raise GenerateError(f"template not found: {template_path}")
    template_text = template_path.read_text(encoding="utf-8")

    root = Path(output_root) if output_root is not None else NEXTNANO_ROOT
    out_dir = root / str(sweep["output_subdir"]).strip() / str(sweep["model_name"]).strip()
    constants = sweep.get("constants") or {}

    results: list[tuple[Path, dict]] = []
    for index, combo in enumerate(expand_grid(sweep), start=1):
        params = {**constants, **combo}
        body = render(template_text, params, template_rel)
        deck_text = _header(template_rel, params) + body
        dest = out_dir / _deck_name(index, combo)
        if not dry_run:
            out_dir.mkdir(parents=True, exist_ok=True)
            # newline="\n": deterministic LF regardless of OS.
            dest.write_text(deck_text, encoding="utf-8", newline="\n")
        results.append((dest, params))
    return results


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate nextnano++ input decks from a template + sweep YAML."
    )
    parser.add_argument("--config", required=True, type=Path, help="Sweep YAML path.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without writing any files.",
    )
    args = parser.parse_args(argv)

    try:
        results = generate(args.config, dry_run=args.dry_run)
    except GenerateError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    verb = "Would generate" if args.dry_run else "Generated"
    print(f"{verb} {len(results)} deck(s) from {args.config}:")
    for dest, params in results:
        pretty = ", ".join(f"{k}={_fmt(params[k])}" for k in sorted(params))
        try:
            shown = dest.relative_to(NEXTNANO_ROOT.parent)
        except ValueError:
            shown = dest
        print(f"  {shown}   [{pretty}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
