"""The three groups, defined once and deterministically.

Group 1  the two supplied ``.nnp`` files, used verbatim
Group 2  20 Latin-hypercube ACQW structures around the paper design
Group 3  the paper's ideal-abrupt benchmark

Nothing here reads a result. The sweep is generated from a fixed seed before
anything is solved, so the twenty structures are a property of the config file
rather than of the order the solver happened to finish in.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np
import yaml

import grading16g

GROUP_NNP = "supplied_nnp"
GROUP_SWEEP = "structure_sweep"
GROUP_PAPER = "paper_benchmark"
GROUPS = (GROUP_NNP, GROUP_SWEEP, GROUP_PAPER)

#: The order the sweep's dimensions are sampled in. Fixed, because the seed only
#: reproduces a design if the columns mean the same thing every time.
SWEEP_DIMENSIONS = (
    "thick_well", "thin_well", "tunnel_barrier", "left_grade", "right_grade",
)


class Cases16GError(ValueError):
    """A case definition that is malformed rather than merely unusual."""


def load_config(path: Path | None = None) -> dict[str, Any]:
    path = Path(path) if path else Path(__file__).resolve().parent / "config16g.yaml"
    if not path.is_file():
        raise Cases16GError(f"no Demo 16G configuration at {path}")
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if payload.get("optics", {}).get("absolute_scale_factor") is not None:
        raise Cases16GError(
            "optics.absolute_scale_factor is set. Demo 16G computes every chi2 "
            "from the physics and must not carry a fitted multiplier; remove it."
        )
    payload["_config_path"] = str(path)
    return payload


# ---------------------------------------------------------------------------
# Case records
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class NnpCase:
    """One supplied ``.nnp`` file, preserved exactly as given."""

    case_id: str
    label: str
    source_path: Path
    group: str = GROUP_NNP

    def as_record(self) -> dict[str, Any]:
        return {
            "group": self.group,
            "case_id": self.case_id,
            "label": self.label,
            "source": str(self.source_path),
            "source_kind": "supplied_nnp_file",
            "structure_generated_by": "the supplied file itself; not regenerated",
        }


@dataclass(frozen=True)
class StructureCase:
    """One ACQW structure this demo builds, from the sweep or the benchmark."""

    case_id: str
    label: str
    group: str
    thick_well_nm: float
    thin_well_nm: float
    tunnel_barrier_nm: float
    left_grade_nm: float
    right_grade_nm: float
    grading_definition: str = grading16g.DEFAULT_DEFINITION
    abrupt_threshold_nm: float = 0.005
    period_barrier_nm: float | None = None
    notes: str = ""

    @property
    def total_well_nm(self) -> float:
        return self.thick_well_nm + self.thin_well_nm

    @property
    def asymmetry_s(self) -> float:
        """``(d1 - d2) / (d1 + d2)``, the paper's structural asymmetry."""

        total = self.total_well_nm
        if total <= 0:
            raise Cases16GError(f"{self.case_id}: total well thickness is not positive.")
        return (self.thick_well_nm - self.thin_well_nm) / total

    @property
    def left_grade(self) -> grading16g.GradeWidths:
        return grading16g.describe(
            self.left_grade_nm, definition=self.grading_definition,
            abrupt_threshold_nm=self.abrupt_threshold_nm,
        )

    @property
    def right_grade(self) -> grading16g.GradeWidths:
        return grading16g.describe(
            self.right_grade_nm, definition=self.grading_definition,
            abrupt_threshold_nm=self.abrupt_threshold_nm,
        )

    @property
    def is_fully_abrupt(self) -> bool:
        return self.left_grade.is_abrupt and self.right_grade.is_abrupt

    def as_record(self) -> dict[str, Any]:
        return {
            "group": self.group,
            "case_id": self.case_id,
            "label": self.label,
            "source": "generated by Demo 16G",
            "source_kind": "generated_structure",
            "thick_well_nm": self.thick_well_nm,
            "thin_well_nm": self.thin_well_nm,
            "barrier_nm": self.tunnel_barrier_nm,
            "total_well_nm": self.total_well_nm,
            "asymmetry_s": self.asymmetry_s,
            "period_barrier_nm": self.period_barrier_nm,
            "left_grade_nm": self.left_grade_nm,
            "right_grade_nm": self.right_grade_nm,
            "grading_definition": self.grading_definition,
            **self.left_grade.as_record("left"),
            **self.right_grade.as_record("right"),
            "fully_abrupt": self.is_fully_abrupt,
            "notes": self.notes,
        }


# ---------------------------------------------------------------------------
# Group 1
# ---------------------------------------------------------------------------


def supplied_nnp_cases(
    cfg: Mapping[str, Any], repository_root: Path,
    overrides: Sequence[str] | None = None,
) -> list[NnpCase]:
    """The supplied files, resolved repository-relative and never edited.

    ``overrides`` replaces the configured paths positionally, so the two files
    can be pointed somewhere else from the CLI without touching the config or
    baking a machine-specific path into the code.
    """

    entries = list(cfg["supplied_nnp"])
    if overrides:
        if len(overrides) > len(entries):
            raise Cases16GError(
                f"{len(overrides)} --nnp-file overrides for {len(entries)} "
                "configured supplied files"
            )
        for index, override in enumerate(overrides):
            entries[index] = {**entries[index], "path": override}
    cases = []
    for entry in entries:
        raw = Path(entry["path"])
        path = raw if raw.is_absolute() else Path(repository_root) / raw
        cases.append(NnpCase(
            case_id=str(entry["id"]), label=str(entry["label"]),
            source_path=path,
        ))
    return cases


# ---------------------------------------------------------------------------
# Group 2 -- Latin hypercube
# ---------------------------------------------------------------------------


def _latin_hypercube(
    count: int, dimensions: int, rng: np.random.Generator
) -> np.ndarray:
    """One LHS design in the unit cube: one sample per stratum per dimension."""

    design = np.empty((count, dimensions), dtype=float)
    for column in range(dimensions):
        permutation = rng.permutation(count)
        jitter = rng.random(count)
        design[:, column] = (permutation + jitter) / count
    return design


def _minimum_pairwise_distance(design: np.ndarray) -> float:
    difference = design[:, None, :] - design[None, :, :]
    distance = np.sqrt((difference**2).sum(axis=-1))
    np.fill_diagonal(distance, np.inf)
    return float(distance.min())


def maximin_design(
    count: int, dimensions: int, *, seed: int, candidates: int = 64
) -> tuple[np.ndarray, dict[str, Any]]:
    """The best of ``candidates`` seeded LHS designs, by maximin distance.

    Plain LHS guarantees one sample per stratum per axis but can still stack
    points along a diagonal. Drawing several designs from the same seeded
    generator and keeping the one whose closest pair is furthest apart costs
    nothing and gives a genuinely space-filling set -- and it stays exactly
    reproducible, because the generator is seeded and the selection rule is
    deterministic.
    """

    rng = np.random.default_rng(int(seed))
    best: np.ndarray | None = None
    best_distance = -1.0
    distances = []
    for _ in range(int(candidates)):
        design = _latin_hypercube(int(count), int(dimensions), rng)
        distance = _minimum_pairwise_distance(design)
        distances.append(distance)
        if distance > best_distance:
            best, best_distance = design, distance
    assert best is not None
    return best, {
        "seed": int(seed),
        "candidates_evaluated": int(candidates),
        "selected_minimum_pairwise_distance": best_distance,
        "candidate_distance_mean": float(np.mean(distances)),
        "candidate_distance_worst": float(np.min(distances)),
        "selection_rule": "maximin over seeded Latin-hypercube candidates",
    }


def sweep_cases(cfg: Mapping[str, Any]) -> tuple[list[StructureCase], dict[str, Any]]:
    """The 20 deterministic structures, plus the design's provenance."""

    sweep = cfg["sweep"]
    ranges = sweep["ranges_nm"]
    count = int(sweep["count"])
    quantum = float(sweep.get("quantize_nm", 0.01))
    threshold = float(sweep.get("abrupt_threshold_nm", 0.005))
    design, provenance = maximin_design(
        count, len(SWEEP_DIMENSIONS), seed=int(sweep["seed"]),
        candidates=int(sweep.get("maximin_candidates", 64)),
    )

    values: dict[str, np.ndarray] = {}
    for index, name in enumerate(SWEEP_DIMENSIONS):
        low, high = (float(v) for v in ranges[name])
        if high < low:
            raise Cases16GError(f"sweep range {name} is inverted: {low}..{high}")
        scaled = low + design[:, index] * (high - low)
        # Quantised so a structure can be rebuilt from the printed table alone.
        values[name] = np.round(scaled / quantum) * quantum

    cases = []
    for row in range(count):
        case_id = f"sweep_{row + 1:02d}"
        cases.append(StructureCase(
            case_id=case_id,
            label=case_id.replace("_", " "),
            group=GROUP_SWEEP,
            thick_well_nm=float(values["thick_well"][row]),
            thin_well_nm=float(values["thin_well"][row]),
            tunnel_barrier_nm=float(values["tunnel_barrier"][row]),
            left_grade_nm=float(values["left_grade"][row]),
            right_grade_nm=float(values["right_grade"][row]),
            grading_definition=cfg["grading"]["definition"],
            abrupt_threshold_nm=threshold,
            period_barrier_nm=float(cfg["numerics"]["domain_padding_nm"]),
        ))

    provenance.update({
        "dimensions": list(SWEEP_DIMENSIONS),
        "ranges_nm": {k: list(v) for k, v in ranges.items()},
        "count": count,
        "quantize_nm": quantum,
        "abrupt_threshold_nm": threshold,
        "grading_definition": cfg["grading"]["definition"],
        "abrupt_cases": [c.case_id for c in cases if c.is_fully_abrupt],
        "note": (
            "regenerating with the same config and seed reproduces these twenty "
            "structures exactly; no result is read at any point"
        ),
    })
    return cases, provenance


# ---------------------------------------------------------------------------
# Group 3
# ---------------------------------------------------------------------------


def paper_benchmark_case(cfg: Mapping[str, Any]) -> StructureCase:
    """The paper's ideal-abrupt ACQW, transcribed and then checked."""

    paper = cfg["paper_benchmark"]
    case = StructureCase(
        case_id="paper_benchmark",
        label="Paper benchmark (ideal abrupt)",
        group=GROUP_PAPER,
        thick_well_nm=float(paper["thick_well_nm"]),
        thin_well_nm=float(paper["thin_well_nm"]),
        tunnel_barrier_nm=float(paper["tunnel_barrier_nm"]),
        left_grade_nm=0.0,
        right_grade_nm=0.0,
        grading_definition=cfg["grading"]["definition"],
        abrupt_threshold_nm=float(cfg["sweep"].get("abrupt_threshold_nm", 0.005)),
        period_barrier_nm=float(paper["period_barrier_nm"]),
        notes=(
            "ideal abrupt interfaces; the structure whose chi2 the paper states "
            "as 2340 pm/V at 1550 nm"
        ),
    )
    # Transcription is checked rather than trusted: these three numbers are the
    # only thing tying this demo to the paper's stated target.
    if abs(case.total_well_nm - float(paper["total_well_nm"])) > 1e-9:
        raise Cases16GError(
            f"paper benchmark total well is {case.total_well_nm} nm, config says "
            f"{paper['total_well_nm']} nm"
        )
    if abs(case.asymmetry_s - float(paper["asymmetry_s"])) > 5e-3:
        raise Cases16GError(
            f"paper benchmark asymmetry is {case.asymmetry_s:.4f}, config says "
            f"{paper['asymmetry_s']}"
        )
    period = case.total_well_nm + case.tunnel_barrier_nm + float(
        paper["period_barrier_nm"]
    )
    if abs(period - float(paper["total_period_nm"])) > 1e-9:
        raise Cases16GError(
            f"paper benchmark period sums to {period} nm, config says "
            f"{paper['total_period_nm']} nm"
        )
    if not case.is_fully_abrupt:
        raise Cases16GError("the paper benchmark must have abrupt interfaces.")
    return case


def all_cases(
    cfg: Mapping[str, Any], repository_root: Path,
    nnp_overrides: Sequence[str] | None = None,
) -> dict[str, Any]:
    """Every case in every group, plus the sweep design's provenance."""

    sweep, provenance = sweep_cases(cfg)
    return {
        GROUP_NNP: supplied_nnp_cases(cfg, repository_root, nnp_overrides),
        GROUP_SWEEP: sweep,
        GROUP_PAPER: [paper_benchmark_case(cfg)],
        "sweep_design": provenance,
        "grading_convention": grading16g.convention_note(cfg["grading"]["definition"]),
    }
