"""Assemble numbered additive home audit; consumes actual computed evidence."""
from pathlib import Path
import csv,json,hashlib

HERE=Path(__file__).resolve().parent
OUT=HERE/'outputs/HOME_EXHAUSTIVE_AUDIT'
EXT=HERE/'outputs/EXTENDED_IMPLEMENTATION_AUDIT'

def read(p):
    with p.open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def writecsv(p,rows):
    keys=list(dict.fromkeys(k for r in rows for k in r))
    with p.open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=keys);w.writeheader();w.writerows(rows)
def row(family,variant,question,method,result,status,evidence,interpretation,plausible='NO',pro='NO',inputs='Existing Demo23D inputs and Demo26 extended artifacts'):
    return dict(family=family,variant=variant,question=question,method=method,input_data=inputs,result=result,status=status,improved='N/A',evidence=evidence,interpretation=interpretation,possible_reason=interpretation,plausible=plausible,pro_required=pro)

def supplemental():
    eng=json.loads((OUT/'engine_verification.json').read_text())
    rows=[]
    rows.append(row('C','Independent engine isolation','Does the independent evaluator call the production engine?','Inspect AST calls of independent_eq2 and source imports.','No production evaluator called','PASS',json.dumps(eng['independent_function_calls']),'Genuinely separate evaluation, but shared input values can still be wrong.'))
    rows.append(row('C','Direct pathway and subtotal comparison','Do independent and production real-input pathways agree?','Execute both engines and compare all 16 pathways and both subtotals.',f"Pathway max {eng['max_pathway_error_pm_per_V']:.4g}; electron subtotal {eng['electron_subtotal_max_error_pm_per_V']:.4g}; HH {eng['hole_subtotal_max_error_pm_per_V']:.4g} pm/V",'PASS','DIRECT_ENGINE_PATHWAY_COMPARISON.csv; engine_verification.json','Ordinary arithmetic/transcription error strongly disfavored for real frozen baseline.'))
    rows.append(row('C','Direct denominator comparison','Do both executed engines construct identical denominators?','Trace production d1/d2 at each pathway and compare every wavelength and k against independent arrays.',f"Maximum error {eng['denominator_max_error_eV']} eV",'PASS','DIRECT_ENGINE_DENOMINATOR_COMPARISON.csv; 16 pathways, 1451 wavelengths, 301 k points, both denominators','This replaces the previous finiteness-only denominator evidence with a numerical comparison.'))
    rows.append(row('C','Final complex comparison','Do final spectra agree with each other and preserved CSV?','Compare full complex arrays.',f"Live engines {eng['baseline_final_max_error_pm_per_V']:.4g}; stored CSV {eng['stored_final_max_error_pm_per_V']:.4g} pm/V",'PASS','engine_verification.json','Roundoff-scale differences cannot explain spectral mismatch.'))
    rows.append(row('D','Literal printed Eq2','Are printed indices, signs, conjugates and permutation implemented?','Inspect local source PDF equation, production and independent source.', 'Independent matches bra/ket expression; production omits conjugation for complex inputs; real baseline unaffected.','INCONCLUSIVE','EQ2_LITERAL_AUDIT.md','Do not extend real-input agreement to general complex matrices.','YES'))
    rows.append(row('S','All scalar sign combinations','Are arbitrary real wavefunction signs irrelevant?','Reuse 16-combination table; re-run original sign gate.', 'All 16 combinations give zero change in saved audit.','PASS','../EXTENDED_IMPLEMENTATION_AUDIT/WAVEFUNCTION_GAUGE_INVARIANCE.csv','Real sign invariance is necessary but weaker than continuous complex phase invariance.'))
    g=eng['continuous_gauge_tests']
    rows.append(row('S','Continuous complex gauge production','Can production accept arbitrary complex wavefunction phases?','Transform O, ze, zh consistently for five phase vectors; execute production.',f"Maximum magnitude change {max(r['production_max_magnitude_change_pm_per_V'] for r in g):.6g} pm/V",'FAIL','CONTINUOUS_COMPLEX_GAUGE_AUDIT.csv','Confirmed latent conjugation bug. It cannot explain current real frozen inputs; do not use this adapter with arbitrary complex inputs unchanged.','YES'))
    rows.append(row('S','Continuous complex gauge independent','Does the conjugated independent engine pass complex gauge checks?','Use the same five phase transformations.',f"Max change {max(r['independent_max_complex_change_pm_per_V'] for r in g):.6g} pm/V",'PASS','CONTINUOUS_COMPLEX_GAUGE_AUDIT.csv','The audit uses this engine for matrix variants; production source preserved.'))
    rows.append(row('T','Coordinate origin','Does translating z change susceptibility?','Reuse shifts -15,-5,0,+5,+15 nm and rerun original gate.','Maximum 1.62e-12 pm/V; relative 1.98e-14.','PASS','../EXTENDED_IMPLEMENTATION_AUDIT/Z_ORIGIN_INVARIANCE.csv','Identity shifts cancel in the orthonormal frozen scalar formulation. This does not prove dominant-component projected states form an orthonormal basis.'))
    rows.append(row('U','Time convention','Does reversing iGamma conjugate chi without changing magnitude?','Reuse +/-Gamma table and re-run original gate.','Expected conjugation and magnitude invariance pass.','PASS','../EXTENDED_IMPLEMENTATION_AUDIT/IGAMMA_TIME_CONVENTION.csv','Consistent time-convention reversal cannot fix magnitude shape.'))
    phase=read(EXT/'GLOBAL_PHASE_DIAGNOSTIC.csv');best=min(phase,key=lambda r:float(r['normalized_RMSE']))
    r=row('U','Global phase scan','Can global complex phase improve projected real shape?','Reuse full 0-360-degree signed/absolute-real scan.',f"Best {best['observable']} phase {best['phase_deg']} degrees RMSE {best['normalized_RMSE']}",'FAIL','../EXTENDED_IMPLEMENTATION_AUDIT/GLOBAL_PHASE_DIAGNOSTIC.csv','Fitted projection can improve error but cannot explain a magnitude-labeled curve.','NO');r['improved']='YES';r['normalized_RMSE']=float(best['normalized_RMSE']);rows.append(r)
    rows.append(row('V','Units and dimensional normalization','Are denominator units and overall susceptibility units consistent?','Audit eV/meV, hc/lambda, angular frequency, nm/m, radial measure and density prefactor.','Denominator conversions consistent; paper-version Nz prose ambiguous for absolute normalization.','INCONCLUSIVE','UNITS_AUDIT.md','Overall factors disappear after normalization; paper-version ambiguity matters for absolute response, not baseline normalized mismatch.','YES'))
    rows.append(row('P','2.296eV resonance inference','Do 540/1080 extrema prove one missing state?','Reassess explicit paper assignment, approximate digitization and interference.', 'Weak as a unique assignment; plausible energy-only clue, not invalid arithmetic.','INCONCLUSIVE','EQ2_LITERAL_AUDIT.md; ../EXTENDED_IMPLEMENTATION_AUDIT/P1_P3_2296EV_REASSESSMENT.md','Coherent extrema need not equal poles. No author assignment of both peaks to one transition.','YES'))
    rows.append(row('Preservation','Original artifact hashes','Were Demo23/24/original26 preserved?','Reconstruct original filtered fingerprints; added audit files excluded.',str(eng['original_artifacts_preserved']),'PASS' if eng['original_artifacts_preserved'] else 'FAIL','ORIGINAL_ARTIFACT_PRESERVATION.csv','Additive audit does not overwrite previous results.'))
    rows.append(row('Safety','No solver execution','Was the audit restricted to existing outputs?','Read audit source and invoked commands; numerical modules load CSV/raw arrays only.','Only Python postprocessing and read-only inspections were run.','PASS','verify_home_engines.py; numerical_home_audit.py; verification log','No new eigenstates or solver output generated.'))
    return rows

def inventory():
    lines=['# Existing Demo26 test inventory','', 'Original outputs and the extended audit are preserved. New feature detection must reject endpoints and distant extrema; old +/-180 nm nearest-feature matches are not accepted as paper peak recovery. The prior extended professor-review file is absent.','', '| Existing artifact | Rows / size | Verification and reuse |','|---|---:|---|']
    records=[]
    for folder in [HERE/'outputs',EXT]:
        for p in sorted(folder.iterdir()):
            if not p.is_file():continue
            n=len(read(p)) if p.suffix=='.csv' else p.stat().st_size
            comment='Parsed and retained; scientific interpretation re-audited in numbered tests.'
            if 'DENOMINATOR' in p.name:comment='Old table only checks shape/finiteness; superseded by direct executed denominator comparison.'
            if 'FEATURE' in p.name:comment='Retained; old feature windows can match wrong extrema. New strict topology is authoritative for this audit.'
            lines.append(f'| {p.relative_to(HERE).as_posix()} | {n} | {comment} |')
            records.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
    (OUT/'EXISTING_DEMO26_TEST_INVENTORY.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    (OUT/'PRIOR_OUTPUT_HASHES.json').write_text(json.dumps(records,indent=2),encoding='utf-8')

def data_tests():
    evidence='EXISTING_REUSABLE_DATA_INVENTORY.md; EXISTING_RAW_DATA_INVENTORY.json'
    specs=[
      ('B','HWHM versus FWHM','Could quoted 5 meV represent FWHM?','Compare denominator Gamma=2.5 versus5 meV in saved gamma sweep.','Magnitude RMSE0.257014 versus0.262391; no recovered full topology.','INCONCLUSIVE','A factor two changes width but does not explain missing peaks.','YES','NO'),
      ('I','BZ definition','Is pi/a the paper BZ radius?','Read printed statement and FCC lattice geometry.','Gamma-X is2pi/a; phrase0.1BZ does not uniquely identify integration bounds.','INCONCLUSIVE','Different radius remains plausible; exact author/friend convention needed.','YES','NO'),
      ('I','0.20pi/a candidate','Can the alternative cutoff be tested from available output?','Search every raw dispersion tree.','Largest available cutoff0.125pi/a, not0.20.','NOT TESTABLE','No extrapolation permitted; request missing output or new same-geometry solve.','YES','YES'),
      ('K','Matrix reconstruction provenance','Are scalar and projected kp8 matrices physically equivalent?','Compare raw projected branch audit with frozen scalar values.','O12 differs0.01540 to0.99895; hole z12 differs1.4324 to12.5114nm.','INCONCLUSIVE','Different component/state constructions: discrepancy is not proof of a same-method integration error.','YES','NO'),
      ('M','Raw state character','Is tracked hh2 heavy-hole-like?','Read k0 raw spinor weights and adjacent-pair means.','hh2 has0%HH and97.5757%LH; alternate pair1+2 is100%HH.','FAIL','The baseline label is not supported by k0 character. Matrix and energy sources must be reconciled.','YES','NO'),
      ('M','Finite-k character tracking','Can state identity be certified through avoided crossings?','Search nonzero-k spinors/envelopes; inspect fixed energy columns.','Energy columns exist; nonzero-k character/overlap exports absent.','NOT TESTABLE','Energy continuity is not wavefunction continuity. Export finite-k characters or overlaps.','YES','YES'),
      ('Y','Exact structure match','Is Demo23 the exact paper ideal structure?','Compare actual ternary_linear layers with ideal paper and table metadata.','Demo23 has1nm grading; ideal paper appears abrupt.','FAIL','Geometry mismatch established at interfaces; causality of missing features is not established.','YES','NO'),
      ('Y','Equivalent abrupt kp8','Does an already-run matching abrupt kp8 result exist?','Search Demo19-26, raw and fixtures.','Abrupt scalar and coarse Free fixtures exist; matching converged abrupt kp8 dispersion absent.','NOT TESTABLE','Scalar diagnostic is available separately, but exact abrupt E(k) needs new output.','YES','YES'),
      ('Z','Poisson setup match','Is production demonstrably paper-equivalent self-consistent Poisson?','Inspect run block, density flags, charge output and fixture provenance.','run quantum only, no Poisson loop; nonzero hole charge output means zero fixed charge is not zero occupation.','INCONCLUSIVE','Paper/friend electrostatics and carrier conditions unspecified.','YES','NO'),
      ('Z','Matching Poisson alternative','Can a matching self-consistent spectrum be reused?','Search completed Poisson raw results.','Different coarse doped fixture exists; matching converged paper-geometry Poisson absent.','NOT TESTABLE','Need exact electrostatic conditions first, then matching solve if files unavailable.','YES','YES'),
      ('L','Finite-k matrix physics','Can physical M(k) replace M(0) using available files?','Search all seven raw datasets for nonzero-k envelope/matrix exports.','Only k00000 matrices/envelopes found.','NOT TESTABLE','No fabricated matrices; finite-k physics useful but necessity for paper reproduction unproved.','YES','YES'),
      ('Y','Temperature or database changes','Can a different temperature/material database be solved from current data?','Search alternate run provenance.','No certified same-geometry controlled alternate temperature/database eigenstates.','NOT TESTABLE','Friend version/database can settle settings; changed eigenstates require output.','YES','YES'),
      ('X','Exact zero and digitization robustness','Do digitized baseline contacts prove exact chi zeros?','Inspect nonnegative45point simulation trace and interpolation spread.','No signed or author uncertainty information; exact zeros not established.','INCONCLUSIVE','Use apparent deep minima, not exact analytic nodes. No experimental error bars invented.','YES','NO'),
      ('Topology','Topology versus fit','Can lower RMSE alone establish reproduction?','Require genuine interior extrema in separate target windows; inspect full ordered extrema and local prominence.','Baseline P1/P3 and Z1/Z2 strict extrema absent; P2=752,P4=1503nm.','PASS','Numerical best fits still require physical validity and matching topology.','NO','NO'),
    ]
    return [row(f,v,q,m,r,s,evidence,i,p,pro) for f,v,q,m,r,s,i,p,pro in specs]

def assemble():
    rows=json.loads((OUT/'numerical_rows.json').read_text())+supplemental()+data_tests()
    if (OUT/'additional_data_rows.json').exists():rows+=json.loads((OUT/'additional_data_rows.json').read_text())
    for i,r in enumerate(rows,1):
        r['test_number']=f'TEST {i:02d}'
        if r.get('evidence') in ('{}','',None):r['evidence']='numerical_metrics.csv; numerical_spectra.csv (matching variant row/column)'
        if r.get('plausible')=='NO' and r['family'] in ('A','B','E','G','H','J','Q','R','global_energy','W'):
            r['plausible']='Not sufficient as a sole explanation in this tested variant; contribution not excluded'
        if r.get('result')=='does not establish reproduction' and 'normalized_RMSE' in r:
            recovered=', '.join(f'{f}={r.get(f+"_nm")}' for f in ('P1','Z1','P2','P3','Z2','P4'))
            r['result']=f"RMSE {r['normalized_RMSE']:.6f}; strict feature locations nm: {recovered}. Full physical reproduction not established."
    writecsv(OUT/'EXHAUSTIVE_HOME_TEST_SUMMARY.csv',rows)
    (OUT/'numbered_tests.json').write_text(json.dumps(rows,indent=2),encoding='utf-8')
    # Separate fit improvements from check success; non-comparable supports never rank together.
    improved=[r for r in rows if r.get('improved')=='YES']
    ranked=sorted([r for r in improved if isinstance(r.get('normalized_RMSE'),(int,float)) and r.get('family')!='X'],key=lambda r:r['normalized_RMSE'])
    stats={'total_tests':len(rows),'improved_agreement':len(improved),'did_not_improve':sum(r.get('improved')=='NO' for r in rows),'fit_not_applicable':sum(r.get('improved')=='N/A' for r in rows),'inconclusive':sum(r['status']=='INCONCLUSIVE' for r in rows),'requires_new_pro':sum(r.get('pro_required')=='YES' for r in rows),'status_counts':{s:sum(r['status']==s for r in rows) for s in ('PASS','FAIL','INCONCLUSIVE','NOT TESTABLE')}}
    (OUT/'audit_counts.json').write_text(json.dumps(stats,indent=2),encoding='utf-8')
    def ids(family):return '; '.join(r['test_number'] for r in rows if r['family']==family)
    hypotheses=[('Different matrix source/state labels','K','Raw hh2 is LH-like; frozen scalar matrices paired with anchored kp8 dispersion','No like-for-like matrix bug proved','High concern, medium causal confidence','Friend matrices, raw state indices, definition of O/z and energy alignment','NO'),('Abrupt structure','Y','Interface mismatch established','No controlled abrupt kp8 comparison; scalar QC failed','Medium','Exact deck and output composition','YES if files absent'),('Different BZ definition/cutoff','I','pi/a versus2pi/a ambiguity; cutoff-sensitive peaks','No0.20pi/a output','Medium','Exact k vector list and integration domain','YES if files absent'),('Schrodinger-Poisson','Z','Production lacks loop; paper says Poisson','Electrostatic conditions unclear; zero doping not proof of spectral effect','Medium-low','Electrostatic boundary conditions, occupations, converged log','YES if files absent'),('Finite-k matrices','L','Could change cancellation','Friend reportedly reproduced withM0; no demonstration of necessity','Unresolved','Exact matrix(k) assumption/export','YES if files absent'),('Different Gamma','B','Some RMSE improvement','No complete topology repair','Low as sole cause','Definition HWHM/FWHM, denominator placement','NO'),('Friend plotted absolute real','A','RMSE0.237873','Paper magnitude label; missing features','Low as sole cause','Exact plotted expression','NO'),('Different pathway subset','E','Offdiagonal RMSE0.221494','Deleting terms not justified','Low as physical remedy','Exact summation code','NO'),('Different equation/complex handling','D','Latent conjugation bug for complex inputs','Baseline real-input agreement excellent','Low for baseline, high implementation concern','Exact code and matrix phases','NO'),('Different wavelength convention','W','Can move features','Paper explicitly fundamental; cannot invent topology','Low','Axis conversion code','NO'),('Different version/database','Y','Could alter bands','No evidence of actual difference yet','Unknown','Version and simulation_database.txt','YES if new solve needed'),('Ordinary radial normalization bug','G','None; normalized constant variants identical','Direct numerical checks pass','Strongly disfavored','Integration weights code','NO')]
    hr=[];rr=[]
    for rank,(h,f,ef,ea,c,need,pro) in enumerate(hypotheses,1):
        hr.append({'Hypothesis':h,'Can test at home?':'Partial; settings can be compared from files','Test number':ids(f),'Result':ef+'; '+ea,'Still plausible?':'Yes as unresolved difference' if rank<=5 else 'Weak as sole explanation','What evidence needed from friend?':need,'Requires Pro?':pro})
        rr.append({'Rank':rank,'Hypothesis':h,'Evidence for':ef,'Evidence against':ea,'Tests supporting conclusion':ids(f),'Can friend settle this?':need,'Needs Pro?':pro,'Confidence':c})
    writecsv(OUT/'FRIEND_REPRODUCTION_HYPOTHESES.csv',hr);writecsv(OUT/'FINAL_HOME_ROOT_CAUSE_RANKING.csv',rr)
    review=OUT/'PHYSICS_PROFESSOR_REVIEW_HOME_EXHAUSTIVE.md'
    lines=['# Demo 26 — Exhaustive Home-Laptop Reproduction Audit','', '## 1. Executive summary','', '**Decision: NEED FRIEND\'S FILES BEFORE RUNNING PRO.**','', 'No defensible full paper reproduction has been established. The real frozen baseline is numerically consistent with the independently implemented printed equation. The strongest new concerns are matrix/state provenance and state-specific energy anchoring, alongside geometry and BZ ambiguity. A latent production complex-conjugation bug is demonstrated, but does not explain the present real-input mismatch. Production files and prior outputs remain preserved.','', 'This is a finite, declared audit of the supplied test families using the searched datasets. It is not a claim that every conceivable home analysis or improved physical reduction is exhausted. Lower RMSE never establishes reproduction by itself.','',json.dumps(stats,indent=2),'', 'Counts overlap: improved/not-improved concern fit metrics; INCONCLUSIVE concerns physical interpretation; Pro-required concerns missing eigenstates. PASS means the stated numerical/provenance check passed, not that the paper was reproduced. Variant rows include repeated baselines as controls, not independent discoveries.','', '## 2. Available data and baseline','', 'See EXISTING_REUSABLE_DATA_INVENTORY.md and EXISTING_DEMO26_TEST_INVENTORY.md. Seven real Professional dispersion datasets include101/201/301 grids and cutoffs0.05/0.075/0.10/0.125pi/a plus45-degree direction. Only k0 wavefunctions/character were exported. Thirteen scalar geometry records include abrupt, but all physical_valid flags are false. Coarse Free abrupt/Poisson fixtures are not converged matching alternatives.','', 'Baseline: Demo23D, frozen case04 scalar M0, statewise-anchored kp8 E(k), 1nm grading, Gamma5meV,16pathways, gs*k*dk/(2pi), magnitude. Wavelength400–1850nm, paper45point linear interpolation, full-window separate normalization. RMSE0.2623911179. Strict target windows: P1 490–580,P2 690–820,P3 990–1170,P4 1450–1610nm; minima use their separately declared windows in numerical_home_audit.py. Missing interior extrema remain null rather than forced endpoints. Baseline P2=752/P4=1503nm; no strict P1/P3/Z1/Z2 extrema. Local errors and target amplitudes are in TEST01.','', '## 3. What cannot be tested without additional eigenstates','']
    for r in rows:
        if r.get('pro_required')=='YES':lines.append(f"- {r['test_number']} {r['variant']}: {r['result']} {r['interpretation']}")
    lines+=['','## 4. Numbered audit','']
    labels=[('question','Question'),('method','Method'),('input_data','Input data'),('result','Result'),('status','Status'),('improved','Improved paper agreement?'),('evidence','Quantitative evidence / file'),('interpretation','Physics interpretation'),('possible_reason','Reason it worked or failed'),('plausible','Hypothesis remains plausible?'),('pro_required','Requires new Pro data?')]
    for r in rows:
        lines += [f"### {r['test_number']} — {r['variant']}",'']
        for key,label in labels:lines.append(f"- **{label}:** {r.get(key,'Not applicable')}")
        met={k:v for k,v in r.items() if 'RMSE' in k or k in ('correlation','all_peaks_nm','all_minima_nm','topology_json') or k.endswith('_nm')}
        if met:lines+=['','```json',json.dumps(met,ensure_ascii=False),'```']
        lines.append('')
    lines+=['## 5. SECTION A — Things that improved agreement','', 'Ranked within the full baseline wavelength domain. Mapping tests use their own shared-support comparator and are not mixed into this ranking. Paper-interpolation tests change the reference measure and are also separate.','']
    for i,r in enumerate(ranked,1):lines.append(f"{i}. {r['test_number']} {r['variant']}: RMSE {r['normalized_RMSE']:.6f}; reduction {(1-r['normalized_RMSE']/0.26239111786932695)*100:.2f}%. {r['interpretation']}")
    lines+=['','## 6. SECTION B — Things that did not fix the paper','']
    for i,r in enumerate([r for r in rows if r.get('improved')=='NO'],1):lines.append(f"{i}. {r['test_number']} {r['variant']}: {r['result']} {r['interpretation']}")
    lines+=['','## 7. Inconclusive results','']
    for r in rows:
        if r['status']=='INCONCLUSIVE':lines.append(f"- {r['test_number']} {r['variant']}: {r['interpretation']}")
    lines+=['','## 8. Existing reusable alternatives','', 'The scalar abrupt/graded variants are internally consistent parabolic diagnostics from each individual matrix/energy record. They are not replacements for kp8 dispersion. Any projected spinor reduction is method-limited; branch averaging is not endorsed as physical. The raw k0 hh2 pair3+4 is97.5757%LH and0%HH. A pureHH pair1+2 exists, but a consistent reduced optical theory is needed. See inventory and additional_data_rows.json.','', '## 9. Friend reproduction hypotheses','', 'FRIEND_REPRODUCTION_HYPOTHESES.csv maps each plausible difference to numbered tests. Ask first for the exact runnable deck PLUS the exact spectrum-generation/postprocessing script, accompanied by raw output/version/database identifiers. This resolves several uncertainties together. A screenshot does not.','', '## 10. Root-cause ranking','']
    for r in rr:lines.append(f"{r['Rank']}. {r['Hypothesis']}: {r['Evidence for']}. Against: {r['Evidence against']}. Confidence: {r['Confidence']}.")
    lines+=['','## 11. Independent physics professor review','', review.read_text(encoding='utf-8') if review.exists() else 'PENDING — independent review not yet delivered. This report is not final until review is incorporated.','', '## 12. SECTION C — Home versus Pro boundary','', 'HOME-COMPLETABLE: compare friend files, reconcile scalar versus kp8 projection and energy anchors, and correct the latent production complex-input conjugation behavior before future complex use. Audit computations already use the independent conjugated engine. Finite-k character certification, matching abrupt kp8, extended0.20pi/a and matching Poisson require missing eigenstates unless the friend already has those outputs.','', '## 13. Recommended next action','', '**NEED FRIEND\'S FILES BEFORE RUNNING PRO.** First compare exact deck, postprocessing, selected states, matrix definitions, energy anchoring, k vector list, Gamma and electrostatics. No demonstrated requirement for full Demo25 yet. No solver was invoked. No production formula was silently modified.','', '## 14. Exact minimum Pro run if files do not resolve it','', 'After matching settings, the smallest useful first discriminator is one exact abrupt-versus-existing-graded kp8 comparison: same nominal7.1/1.8/2.9nm design and outer barriers, material database, temperature, k direction,301points and0.10pi/a; change only interface grading to abrupt. Export k0 full complex spinors/matrices, per-k state character and energies; include eigenvectors needed to track states if supported. Reconcile states/energy reference and compute the same justified M0 reduction offline. Do not change Poisson, cutoff and geometry together. If the friend instead specifies0.20pi/a or a different electrostatic solve, that matched convention becomes the targeted discriminator. Full finite-k M(k) campaign is not yet justified by this audit alone.','']
    (OUT/'DEMO26_HOME_EXHAUSTIVE_FINAL_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
    print(json.dumps(stats,indent=2))

if __name__=='__main__':
    OUT.mkdir(parents=True,exist_ok=True)
    inventory()
    (OUT/'supplemental_test_rows.json').write_text(json.dumps(supplemental(),indent=2),encoding='utf-8')
    assemble()
