"""Render the beginner guides in ``guides/`` from the catalogue, not by hand.

A hand-written guide is stale the moment a column is renamed, and prose does not
fail a test.  These are generated from :mod:`catalog13`, whose entries are in
turn checked against the code that produces the artifacts, so a figure that
gains or loses a column cannot quietly keep its old description.

Run ``python guides13.py`` to regenerate. The tests in
``test_demo13_guides.py`` fail if the files on disk differ from what this module
produces, so a stale guide is a test failure rather than a discovery.
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Any, Mapping

DEMO_DIR = Path(__file__).resolve().parent
SHARED = DEMO_DIR.parent / "_shared"
DEMO12_DIR = DEMO_DIR.parent / "12_graded_interface_coupled_quantum_well_optimization"
for _path in (str(SHARED), str(DEMO12_DIR), str(DEMO_DIR)):
    if _path not in sys.path:
        sys.path.insert(0, _path)

import catalog13  # noqa: E402
import plots13  # noqa: E402
import report13  # noqa: E402
import tables13  # noqa: E402

GUIDES_DIR = DEMO_DIR / "guides"

#: Repeated verbatim wherever a chi(2) number appears, so no guide can drift
#: into implying an absolute scale.
UNITS_WARNING = (
    "**Units.** Every chi(2) number in this demo is a *relative* merit in "
    "arbitrary units (`a.u. (relative |chi2|)`). It is a lineshape and a trend "
    "with no absolute calibration. It is **never pm/V**, and values are only "
    "comparable between designs computed with the same mesh and settings."
)

#: The v3 headline, stated once and reused, so the guides cannot disagree.
V3_STATUS = (
    "**Current result (experiment v3).** 23 proposals, 7 refused before the "
    "solver ran, 16 completed with no solver failures, **3 feasible**. The best "
    "feasible trial is **t0021** (asymmetry 0.387565, central barrier 0.85 nm, "
    "abrupt, relative chi2 at 1550 nm = 0.411027, detuning -13 nm). t0021 sits "
    "on the barrier **lower bound** and Stage 5 has not run, so it is the best "
    "design *found*, **not a validated optimum**."
)


def _header(title: str) -> list[str]:
    return [f"# {title}", "", "_Generated by `guides13.py` — edit that, not this file._", ""]


def readme() -> str:
    lines = _header("Demo 13 guides")
    lines += [
        "Demo 13 uses **Bayesian optimization** to search for an asymmetric "
        "coupled quantum well with the strongest second-order nonlinear response "
        "at 1550 nm, subject to physical quality constraints.",
        "",
        "## How the search works",
        "",
        "1. **Sobol phase** — a handful of quasi-random designs, to give the model "
        "something to learn from.",
        "2. **Model-based (MBM) phase** — a Gaussian-process surrogate proposes "
        "each next design, balancing predicted strength against uncertainty.",
        "3. **Preflight** — every proposal is checked *before* the solver runs. An "
        "unbuildable geometry is refused, costs no solver time, and does not "
        "consume a BO iteration.",
        "4. **Evaluation** — nextnano++ solves the accepted design; the response "
        "and quality metrics are extracted and returned to the optimizer.",
        "",
        "A proposal is therefore not the same thing as an evaluation, and this "
        "distinction runs through every guide here.",
        "",
        V3_STATUS,
        "",
        UNITS_WARNING,
        "",
        "## Where things live",
        "",
        "| What | Where |",
        "|---|---|",
        "| Experiment state (protected) | `nextnano/results/demo_runs/13_ax_bayesian_optimization_graded_acqw/demo13_ax_experiment_v3/` |",
        "| Ax snapshot | `<experiment>/ax_experiment_snapshot.json` |",
        "| Immutable trial ledger | `<experiment>/trial_ledger.jsonl` |",
        "| Search-space identity | `<experiment>/experiment_schema.json` |",
        "| Report bundles (one per run) | `nextnano/results/demo_runs/13_.../<UTC timestamp>_<hash>/` |",
        "| Figures | `<bundle>/plots/` |",
        "| Numbers behind each figure | `<bundle>/plot_data/` |",
        "| Result tables | `<bundle>/tables/` |",
        "",
        "The experiment directory is **never** modified by an analysis run. Report "
        "bundles are disposable and can be regenerated at any time.",
        "",
        "## Reading order",
        "",
        "1. `INPUT_PARAMETERS_GUIDE.md` — what you can change, and what it does",
        "2. `OUTPUT_RESULTS_GUIDE.md` — what every result number means",
        "3. `PLOTS_GUIDE.md` — what every figure shows, and what it cannot show",
        "4. `TABLES_GUIDE.md` — what every table contains",
        "5. `WORK_LAPTOP_GUIDE.md` — exact commands, safe ones marked clearly",
        "6. `TROUBLESHOOTING_GUIDE.md` — when something looks wrong",
        "",
        "## Audit reports",
        "",
        "`V3_FINAL_TEST_REPORT.md`, `V3_FINAL_SOFTWARE_AUDIT.md`, "
        "`V3_FINAL_PHYSICS_AUDIT.md`, `V3_FINAL_PLOT_TABLE_AUDIT.md`, "
        "`V3_FINAL_GUIDE_COVERAGE_AUDIT.md`, `V3_WORK_LAPTOP_READINESS.md`, "
        "`V3_FINAL_CROSS_AUDIT.md`, `V3_FINAL_STALE_CODE_AUDIT.md`, "
        "`V3_PLOT_AND_TABLE_FUNCTION_AUDIT.md`.",
        "",
        "## Vocabulary that is easy to mix up",
        "",
        "| Term | Means |",
        "|---|---|",
        "| proposal | a design Ax suggested — it may never have been simulated |",
        "| completed trial | a design the solver actually evaluated |",
        "| refused / rejected proposal | refused at preflight; **no solver ran** |",
        "| feasible trial | completed *and* satisfied every constraint |",
        "| Sobol evaluation | one of the quasi-random initial designs |",
        "| MBM iteration | one *completed* model-based evaluation, numbered 1-10 |",
        "| proposed geometry | what the optimizer asked for |",
        "| realized geometry | what the deck actually built — the only physical one |",
        "| observed | measured by the solver |",
        "| surrogate prediction | the model's belief, not a measurement |",
        "",
    ]
    return "\n".join(lines) + "\n"


def plots_guide() -> str:
    lines = _header("Demo 13 plots guide")
    lines += [
        "One entry per figure. Every figure has a CSV of exactly the numbers "
        "drawn, at the path given.",
        "",
        V3_STATUS, "", UNITS_WARNING, "",
        "**Observed vs predicted.** Evaluated designs are drawn as markers and "
        "are never smoothed. Continuous surfaces are *surrogate predictions* with "
        "the evaluated points overlaid, so the two cannot be confused.",
        "",
        "**A missing figure is a bug, not a licence problem.** A figure with no "
        "data becomes a labelled placeholder whose text says why.",
        "", "---", "",
    ]
    for filename, short in plots13.PLOT_SET:
        entry = report13.PLOT_GUIDE.get(filename, {})
        note = catalog13.PLOT_NOTES.get(filename, {})
        lines += [
            f"## `{filename}`", "",
            f"**{short}.** {entry.get('question', '')}", "",
            f"- **Data behind it:** `{catalog13.plot_csv_name(filename)}`",
            f"- **x-axis:** {entry.get('x', 'n/a')}",
            f"- **y-axis:** {entry.get('y', 'n/a')}",
            f"- **Colour / marker:** {entry.get('encoding', 'n/a')}",
            f"- **Included:** {catalog13.plot_population(filename)}",
            f"- **Data type:** {entry.get('data', 'n/a')}",
            "",
            f"**How to read it.** {entry.get('read', '')}",
            "",
            f"**What it cannot tell you.** {entry.get('limits', '')}",
            "",
            f"**In v3.** {note.get('v3', '')}",
            "",
        ]
    return "\n".join(lines) + "\n"


def tables_guide() -> str:
    lines = _header("Demo 13 tables guide")
    lines += [
        "Every table is a **projection of the immutable trial ledger**, rebuilt "
        "from it on each run, so regenerating a table can never put history at "
        "risk. Each CSV has a `.units.json` sidecar naming the unit of every "
        "column.",
        "", V3_STATUS, "", UNITS_WARNING, "",
        "**No table silently drops a trial.** Invalid and refused proposals have "
        "their own tables *and* stay in the complete history with their reason.",
        "", "---", "",
    ]
    for name in sorted(tables13.TABLE_CATALOGUE):
        lines += [
            f"## `{name}.csv`", "",
            f"One row = {tables13.TABLE_CATALOGUE[name]}.", "",
            f"- **Units sidecar:** `{name}.units.json`",
            "",
        ]
    lines += [
        "---", "",
        "## The four tables that answer 'what happened?'", "",
        "| Table | Question it answers |",
        "|---|---|",
        "| `bo_budget_accounting` | How many proposals, refusals, evaluations? |",
        "| `bo_candidate_rejection_history` | Why was each refused proposal refused? |",
        "| `bo_trial_iteration_mapping` | Which trial was which BO iteration? |",
        "| `bo_proposed_vs_realized_grading` | What was asked for vs what was built? |",
        "",
        "### Common mistakes", "",
        "- Reading the ledger's `iteration` column as the BO iteration. It counts "
        "**proposal attempts** and reached 17 in a 10-iteration study. Use "
        "`mbm_iteration_number` from `bo_trial_iteration_mapping`.",
        "- Treating a refused proposal as a failed trial. Nothing was simulated; "
        "its `realized_interface_mode` is `not_realized`, not `abrupt`.",
        "- Comparing objectives across feasible and infeasible trials. Only the 3 "
        "feasible v3 trials are comparable as candidate designs.",
        "- Reading `parameter_grading_thickness_nm` on a *refused* row. That column "
        "holds the canonicalized design and shows 0 nm; use the proposed columns.",
        "",
    ]
    return "\n".join(lines) + "\n"


def input_parameters_guide() -> str:
    lines = _header("Demo 13 input parameters guide")
    lines += [
        "Everything you can change, what it does, and whether changing it makes "
        "an existing optimization checkpoint unusable.",
        "",
        "**Checkpoint invalidation.** Some settings define *what the search space "
        "is*. Changing one means the stored trials describe a different problem, "
        "so Demo 13 refuses to resume and tells you to start a new experiment "
        "directory. That refusal is a safety feature.",
        "",
        "**The geometry rule that surprises people.** The widest grade a design "
        "can build is `central barrier thickness - minimum_flat_region_nm`. With "
        "a 0.10 nm flat region and a 0.80 nm minimum resolvable grade, an "
        "**abrupt** design may use the full 0.85 nm barrier, but a **genuinely "
        "graded** design needs a barrier of at least **0.90 nm**. Between 0.85 and "
        "0.90 nm the graded branch is empty and such proposals are refused.",
        "", "---", "",
    ]
    for entry in catalog13.PARAMETER_NOTES:
        lines += [
            f"## `{entry['path']}`", "",
            f"**{entry['plain']}**", "",
            f"- **Type:** {entry['kind']}",
            f"- **Units:** {entry['units']}",
            f"- **Raising it:** {entry['increase']}",
            f"- **Lowering it:** {entry['decrease']}",
            f"- **Interacts with:** {entry['interacts']}",
            f"- **Invalidates an existing checkpoint:** "
            f"{'yes' if entry['invalidates_checkpoint'] else 'no'}",
            "",
        ]
    return "\n".join(lines) + "\n"


def output_results_guide() -> str:
    lines = _header("Demo 13 output results guide")
    lines += [
        "What every important result number means, and how to avoid "
        "over-reading it.",
        "", UNITS_WARNING, "",
        "## The four things that decide whether a design is any good", "",
        "1. **Objective** — `relative_chi2_at_target_wavelength_abs`, higher is better.",
        "2. **Detuning** — `absolute_detuning_nm` must be <= 15 nm. In v3 this is "
        "what failed 13 of 16 completed trials.",
        "3. **Confinement** — `maximum_boundary_probability` must be <= 1e-3.",
        "4. **State identity** — `state_tracking_confidence` must be >= 0.8.",
        "",
        "**A high objective is not enough.** A design with the strongest response "
        "and a 20 nm detuning is *infeasible*, and the best-so-far curve will not "
        "move for it.",
        "", V3_STATUS, "", "---", "",
    ]
    for name in sorted(catalog13.METRIC_NOTES):
        note = catalog13.METRIC_NOTES[name]
        unit = tables13.unit_for(name)
        lines += [
            f"## `{name}`", "",
            f"**{note['plain']}**", "",
            f"- **Units:** {unit}",
            f"- **Direction:** {note['direction']}",
            f"- **How it is computed:** {note['definition']}",
            f"- **Caution:** {note['caution']}",
            "",
        ]
    lines += [
        "---", "",
        "## Statements this data supports, and statements it does not", "",
        "| Statement | Supported? |",
        "|---|---|",
        "| 16 trials completed with no solver failures | **yes** |",
        "| t0021 is the best *feasible* design found | **yes** |",
        "| 7 proposals were geometrically unbuildable and never ran | **yes** |",
        "| t0021 is an optimum | **no** — it sits on the barrier lower bound and Stage 5 has not run |",
        "| 0.85 nm is the best barrier thickness | **no** — it is the bound, and the objective was still rising at it |",
        "| grading helps / hurts | **no** — 5 graded designs, all infeasible |",
        "| erf is the best profile | **no** — erf 3, sigmoid 1, cosine 1, linear 0 trials |",
        "| the graded trials realized their requested profiles | **no** — no alloy-composition output has ever been checked |",
        "| chi2 = 0.411 pm/V | **no** — the scale is relative and arbitrary |",
        "| v3 beats v2 | **no** — different mesh and search space; not comparable |",
        "",
    ]
    return "\n".join(lines) + "\n"


def work_laptop_guide() -> str:
    lines = _header("Demo 13 work-laptop guide")
    lines += [
        "Commands are marked **SAFE** or **SPENDS SOLVER TIME**. Read the marking "
        "before running anything.",
        "",
        "> **SAFE** — reads existing results. No nextnano process starts. The "
        "experiment directory is opened read-only.",
        ">",
        "> **SPENDS SOLVER TIME** — launches licensed nextnano++ jobs. Requires "
        "explicit authorization.",
        "", "---", "",
        "## 1. Pull the latest commit — SAFE", "",
        "```powershell", "git pull", "```", "",
        "## 2. Confirm a clean tree — SAFE", "",
        "```powershell", "git status --porcelain", "```", "",
        "Must print nothing. The v3 campaign was run from a **dirty** tree, so its "
        "recorded commit does not fully describe the code that produced it. Do not "
        "repeat that.",
        "",
        "## 3. Confirm the commit — SAFE", "",
        "```powershell", "git rev-parse HEAD", "```", "",
        "## 4. Activate the environment — SAFE", "",
        "```powershell", "conda activate llm", "```", "",
        "## 5. Confirm the pinned Ax version — SAFE", "",
        "```powershell",
        "python -c \"import ax, botorch, torch; print(ax.__version__, botorch.__version__, torch.__version__)\"",
        "```", "",
        "Expect Ax `1.3.1`.", "",
        "## 6. Run the focused Demo 13 tests — SAFE", "",
        "```powershell",
        "python -m pytest .\\nextnano\\tests\\test_demo13_v3_accounting.py .\\nextnano\\tests\\test_demo13_v3_reporting.py .\\nextnano\\tests\\test_demo13_guides.py -q",
        "```", "",
        "## 7. Run the whole nextnano suite — SAFE", "",
        "```powershell", "python -m pytest .\\nextnano\\tests\\ -q", "```", "",
        "## 8. Check the configuration before running anything — SAFE", "",
        "```powershell",
        "python -c \"import yaml;c=yaml.safe_load(open('nextnano/demos/13_ax_bayesian_optimization_graded_acqw/demo.yaml'));w=c['workflow'];print('mode        :',w['mode']);print('experiment  :',w['experiment_state_dir']);print('run_solver  :',c['simulation']['run_solver'])\"",
        "```", "",
        "**Before any analysis run, `mode` must be `analyze_existing_results`.** If "
        "it says `closed_loop`, the next command would spend licensed solver time.",
        "",
        "## 9. Locate the experiment state — SAFE", "",
        "```powershell",
        "Get-ChildItem .\\nextnano\\results\\demo_runs\\13_ax_bayesian_optimization_graded_acqw\\ -Directory | Select-Object Name",
        "```", "",
        "Expect `demo13_ax_experiment_v3`.", "",
        "## 10. Record protected-file hashes BEFORE — SAFE", "",
        "```powershell",
        "python -c \"import hashlib,pathlib;d=pathlib.Path('nextnano/results/demo_runs/13_ax_bayesian_optimization_graded_acqw/demo13_ax_experiment_v3');[print(n, hashlib.sha256((d/n).read_bytes()).hexdigest()) for n in ('ax_experiment_snapshot.json','trial_ledger.jsonl','experiment_schema.json','demo_yaml_snapshot.yaml')]\"",
        "```", "",
        "## 11. Regenerate every report — SAFE (no solver)", "",
        "```powershell",
        "python .\\nextnano\\demos\\13_ax_bayesian_optimization_graded_acqw\\run_demo13.py",
        "```", "",
        "Expect exit code 0 and a console block reporting 23 proposals, 7 refused, "
        "16 completed, 3 feasible, optimization completed = True, and "
        "`experiment state : unchanged after reanalysis`.",
        "",
        "## 12. Verify zero solver calls — SAFE", "",
        "```powershell",
        "Select-String -Path (Get-ChildItem .\\nextnano\\results\\demo_runs\\13_ax_bayesian_optimization_graded_acqw\\2026* -Directory | Sort-Object Name | Select-Object -Last 1).FullName\\console.log -Pattern 'Executing','Generated new trial'",
        "```", "",
        "Must return **nothing**.", "",
        "## 13. Record protected-file hashes AFTER — SAFE", "",
        "Rerun the command from step 10. All four hashes must be identical.", "",
        "## 14. Collect supplemental raw profiles — SAFE (copies only)", "",
        "```powershell",
        "python .\\nextnano\\scripts\\bundle_raw_trials.py --experiment demo13_ax_experiment_v3 --dry-run",
        "```", "",
        "Then, to actually copy:", "",
        "```powershell",
        "python .\\nextnano\\scripts\\bundle_raw_trials.py --experiment demo13_ax_experiment_v3",
        "```", "",
        "This is read-only with respect to the experiment. It copies generated "
        "inputs, logs, resolved configurations and alloy-composition profiles for "
        "t0021, t0022, t0017, t0005 and every genuinely graded trial, and writes a "
        "manifest naming anything requested but unavailable.",
        "",
        "**Why this matters:** no realized grading profile has ever been verified. "
        "Until these files are transferred, every statement about the shape of a "
        "graded interface rests on arithmetic, not on solver output.",
        "", "---", "",
        "## Stage 5 — PREPARED, NOT AUTHORIZED", "",
        "> **SPENDS SOLVER TIME — approximately 42 licensed runs. Do not run "
        "without explicit authorization.**",
        "",
        "Stage 5 is fully specified in `V3_STAGE5_EXECUTION_PLAN.md`. Before it "
        "may run:",
        "",
        "1. this reanalysis must pass with all four hashes unchanged;",
        "2. the working tree must be clean;",
        "3. `validation_study.output_state_dir` must point somewhere **other than** "
        "`demo13_ax_experiment_v3` — the configuration is rejected otherwise;",
        "4. the mesh gate (2 runs on t0021) must pass before the other 40.",
        "",
        "The launch command is deliberately **not** written out here. Read the "
        "execution plan, confirm the gates, and set `workflow.mode` yourself.",
        "",
        "## Commands that spend solver time — recognise these", "",
        "| Setting | Effect |",
        "|---|---|",
        "| `workflow.mode: closed_loop` | proposes and evaluates new designs |",
        "| `workflow.mode: run_pending_candidates` | evaluates already-generated inputs |",
        "| `workflow.mode: validate_top_designs` | runs Stage 5 |",
        "| `workflow.mode: analyze_existing_results` | **safe** — no solver |",
        "| `workflow.mode: synthetic_smoke_test` | **safe** — no solver, synthetic surface |",
        "",
    ]
    return "\n".join(lines) + "\n"


def troubleshooting_guide() -> str:
    entries: tuple[tuple[str, str, str], ...] = (
        ("`analysis mode found no Ax snapshot in ...`",
         "`workflow.experiment_state_dir` names a directory that does not exist.",
         "The error lists the directories that DO hold a snapshot. Set the setting "
         "to the one you meant. Analysis mode deliberately refuses to create an "
         "empty experiment, because it would then be reported as if it were the "
         "real campaign."),
        ("`cannot resume this experiment: the Ax search space has changed`",
         "A setting that defines the search space differs from the one the "
         "snapshot was written with.",
         "The message names the exact field and both values. Either restore the "
         "configuration, or point `experiment_state_dir` at a NEW directory. The "
         "old one is never modified."),
        ("Reanalysis prints `Generated new trial`",
         "The run is not in analysis mode.",
         "Stop it. Set `workflow.mode: analyze_existing_results`. In analysis mode "
         "the experiment is opened read-only and generation raises."),
        ("Reanalysis prints `Executing ... case.in`",
         "The run is not in analysis mode, and it is spending licensed solver time.",
         "Stop immediately and check `workflow.mode`."),
        ("`refusing to ...: this experiment was opened read-only for analysis`",
         "Something tried to mutate a protected experiment during analysis.",
         "This is the guard working correctly. Report it — analysis should never "
         "attempt a write."),
        ("Surrogate plots are placeholders",
         "No predictive model could be reconstructed.",
         "Read `extracted/analysis_model_reconstruction.json`; `fit_status_reason` "
         "says why. This is a MODEL problem, never a missing-solver problem."),
        ("Surrogate surfaces look sparse or patchy",
         "Usually correct behaviour, not a bug.",
         "Grid points whose realized grade would fall below 0.80 nm are withheld "
         "from the graded branch, because their physical structure is abrupt. Each "
         "withheld row carries the reason in the CSV."),
        ("`bo_candidate_rejection_history.csv` is empty",
         "Historically: it was built from in-memory loop state that reanalysis "
         "never has.",
         "It is now rebuilt from the ledger. An empty table means the ledger has no "
         "rejected records — check the ledger directly."),
        ("Run status says `failed` but nothing failed",
         "Refused proposals were being counted as solver cases.",
         "Fixed: refusals are excluded from the case list. On a machine with no "
         "solver the status is `dry_run_complete`, which is correct."),
        ("`optimization_completed` is false after a finished campaign",
         "It used to read a key the planner never returned.",
         "It now reads the authoritative accounting. Check "
         "`extracted/campaign_accounting.json`."),
        ("Refused proposals described as duplicates",
         "The lifecycle text was hardcoded.",
         "Fixed. A refusal is only a duplicate when its reason says so; v3 had "
         "**zero** duplicates and seven sub-resolution refusals."),
        ("BO iteration numbers run past the configured budget",
         "The ledger's `iteration` column counts proposal ATTEMPTS.",
         "Use `mbm_iteration_number` from `bo_trial_iteration_mapping.csv`, which "
         "runs 1-10 over completed model-based evaluations."),
        ("Reading the wrong report bundle",
         "Bundles are timestamped and never overwritten.",
         "Sort by name and take the last: bundle names are UTC timestamps."),
        ("Composition / alloy-profile figures are empty",
         "The transferred bundle contains no raw solver output.",
         "Run `bundle_raw_trials.py` on the work laptop. Until then, no claim "
         "about a realized grading profile has evidence behind it."),
        ("Stage 5 writing into the v3 experiment directory",
         "Stage 5 must not share a directory with the protected campaign.",
         "Set `validation_study.output_state_dir` to a separate directory. The "
         "configuration is rejected at startup if it points at the optimization "
         "experiment."),
        ("Git tree is dirty before a licensed run",
         "The results could not be attributed to a commit.",
         "Commit or stash first. v3 was run from a dirty tree and its provenance "
         "is correspondingly weaker."),
    )
    lines = _header("Demo 13 troubleshooting guide")
    lines += ["Symptom, cause, and what to do.", "", "---", ""]
    for symptom, cause, action in entries:
        lines += [f"## {symptom}", "", f"**Cause.** {cause}", "",
                  f"**Do this.** {action}", ""]
    return "\n".join(lines) + "\n"


GUIDE_FILES: Mapping[str, Any] = {
    "README.md": readme,
    "PLOTS_GUIDE.md": plots_guide,
    "TABLES_GUIDE.md": tables_guide,
    "INPUT_PARAMETERS_GUIDE.md": input_parameters_guide,
    "OUTPUT_RESULTS_GUIDE.md": output_results_guide,
    "WORK_LAPTOP_GUIDE.md": work_laptop_guide,
    "TROUBLESHOOTING_GUIDE.md": troubleshooting_guide,
}


def write_all(directory: Path | None = None) -> list[Path]:
    target = Path(directory) if directory else GUIDES_DIR
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, builder in GUIDE_FILES.items():
        path = target / name
        path.write_text(builder(), encoding="utf-8", newline="\n")
        written.append(path)
    return written


if __name__ == "__main__":
    for path in write_all():
        print(f"wrote {path}")
