"""Render and check the nextnano++ decks. Defaults reproduce the Demo 26 dataset deck."""
from __future__ import annotations

import re
from pathlib import Path

KP8_DEFAULTS = {
    "temperature_K": 300.0, "substrate": "GaAs", "barrier_alloy_x": 0.55, "total_nm": 30.0,
    "wells_nm": [[9.1, 16.2], [18.0, 20.9]], "interface_model": "linear_1nm", "grade_width_nm": 1.0,
    "coarse_spacing_nm": 0.5, "fine_spacing_nm": 0.05, "quantum_region_nm": [7.1, 22.9],
    "num_electrons": 6, "num_holes": 8, "output_states": 14,
    "k_direction": [0, 1, 0], "k_max_per_nm": 0.555714439232, "k_points": 301,
}


def _f(x: float) -> str:
    return "%.12g" % float(x)


def render_kp8(params: dict | None = None, header: str = "Demo26_Condensed kp8 dispersion deck") -> str:
    p = {**KP8_DEFAULTS, **(params or {})}
    if p["interface_model"] not in ("linear_1nm", "abrupt"):
        raise ValueError("interface_model must be 'linear_1nm' or 'abrupt'")
    if p["k_points"] < 2 or p["k_max_per_nm"] <= 0:
        raise ValueError("k_points >= 2 and k_max_per_nm > 0 required")
    (a1, b1), (a2, b2) = p["wells_nm"]
    x, g = p["barrier_alloy_x"], p["grade_width_nm"] / 2
    lines = "\n".join(f"        line{{ pos = {_f(v)} spacing = {_f(s)} }}" for v, s in
                      [(0, p["coarse_spacing_nm"]), (a1, p["fine_spacing_nm"]), (b1, p["fine_spacing_nm"]),
                       (a2, p["fine_spacing_nm"]), (b2, p["fine_spacing_nm"]), (p["total_nm"], p["coarse_spacing_nm"])])
    grades = ""
    if p["interface_model"] == "linear_1nm":
        rows = []
        for pos, ramp in ((a1, [x, 0]), (b1, [0, x]), (a2, [x, 0]), (b2, [0, x])):
            lo, hi = _f(pos - g), _f(pos + g)
            rows.append(f'    region{{ line{{ x = [{lo}, {hi}] }} ternary_linear{{ name = "Al(x)Ga(1-x)As" '
                        f'alloy_x = [{_f(ramp[0])}, {_f(ramp[1])}] x = [{lo}, {hi}] }} }}')
        grades = "\n" + "\n".join(rows)
    kd = [c * p["k_max_per_nm"] for c in p["k_direction"]]
    q0, q1 = p["quantum_region_nm"]
    n = p["output_states"]
    return f"""# {header}
# Generated by src/decks.py. Edit config/runner.json, not this file.

global{{
    simulate1D{{}}
    temperature = {_f(p["temperature_K"])}
    substrate{{ name = "{p["substrate"]}" }}
    crystal_zb{{ x_hkl = [1, 0, 0]  y_hkl = [0, 1, 0] }}
}}

contacts{{ fermi{{ name = qw_contact  bias = 0.0 }} }}

grid{{
    xgrid{{
{lines}
    }}
}}

structure{{
    output_region_index{{ boxes = no }}
    output_material_index{{ boxes = no }}
    output_alloy_composition{{ boxes = no }}
    region{{ everywhere{{}} ternary_constant{{ name = "Al(x)Ga(1-x)As" alloy_x = {_f(x)} }} }}
    region{{ line{{ x = [0, {_f(p["total_nm"])}] }} contact{{ name = qw_contact }} }}
    region{{ line{{ x = [{_f(a1)}, {_f(b1)}] }} binary{{ name = "GaAs" }} }}
    region{{ line{{ x = [{_f(a2)}, {_f(b2)}] }} binary{{ name = "GaAs" }} }}{grades}
}}

classical{{
    Gamma{{}}
    HH{{}}
    LH{{}}
    SO{{}}
    output_bandedges{{ averaged = no }}
    output_bandgap{{}}
}}

quantum{{
    region{{
        name = "acqw"
        x = [{_f(q0)}, {_f(q1)}]
        no_density = yes
        boundary{{ x = dirichlet }}
        kp_8band{{
            num_electrons = {int(p["num_electrons"])}
            num_holes     = {int(p["num_holes"])}
            k_integration_disabled{{}}
            dispersion{{
                path{{
                    name = "Gamma_to_y"
                    point{{ k = [0, 0, 0] }}
                    point{{ k = [{", ".join(_f(c) for c in kd)}] }}
                    num_points = {int(p["k_points"])}
                }}
                output_k_vectors{{}}
                output_dispersions{{ max_num = {n} }}
                output_masses{{ max_num = {n} }}
            }}
            classify_by_energy{{}}
        }}
        output_states{{
            max_num = {n}
            all_k_points = yes
            envelopes = yes
            envelopes_CB_HH_LH_SO = yes
            probabilities = yes
            probabilities_partial_CB_HH_LH_SO = yes
            spinor_composition = yes
            spinor_composition_CB_HH_LH_SO = yes
            in_one_file = no
        }}
        transition_energies{{ all_k_points = yes  KP8{{}} }}
        dipole_moment_matrix_elements{{
            polarization{{ name = "growth_z" re = [1, 0, 0] }}
            all_k_points = yes
            KP8{{}}
        }}
        momentum_matrix_elements{{
            polarization{{ name = "growth_z" re = [1, 0, 0] }}
            polarization{{ name = "inplane_y" re = [0, 1, 0] }}
            all_k_points = yes
            KP8{{}}
            output_matrix_elements = yes
            output_oscillator_strengths = yes
        }}
    }}
}}

run{{ quantum{{}} }}
"""


_TOKEN = re.compile(r'"[^"]*"|[{}\[\]=,]|[^\s{}\[\]=,]+')


def tokens(text: str) -> list:
    """Comment-free tokens; numbers become floats so 300 == 300.0."""
    body = "\n".join(line.split("#", 1)[0] for line in text.splitlines())
    out = []
    for t in _TOKEN.findall(body):
        try:
            out.append(float(t))
        except ValueError:
            out.append(t)
    return out


def same_deck(a: str, b: str) -> bool:
    return tokens(a) == tokens(b)


def static_check(text: str, kind: str) -> list[str]:
    """Return a list of problems (empty = PASS). Grammar is checked by --parse, not here."""
    compact = "".join("".join(line.split("#", 1)[0].split()) for line in text.splitlines())
    required = ["simulate1D{}", "no_density=yes", "x=dirichlet", "run{quantum{}}",
                'name="GaAs"', 'name="Al(x)Ga(1-x)As"']
    required += (["kp_8band{", "k_integration_disabled{}", "dispersion{", "envelopes_CB_HH_LH_SO=yes",
                  "spinor_composition_CB_HH_LH_SO=yes", "dipole_moment_matrix_elements{"]
                 if kind == "kp8" else ["Gamma{num_ev=6}", "HH{num_ev=6}", "envelopes=yes"])
    problems = [f"missing '{r}'" for r in required if r not in compact]
    if compact.count("{") != compact.count("}"):
        problems.append("unbalanced braces")
    return problems


def read(path: Path) -> str:
    return Path(path).read_text(encoding="utf-8")
