"""One Professional acquisition; preflight and strict returned-data validation.

Never imports the historical input builder. No physics solve unless --run.
"""
import argparse
from datetime import datetime,timezone
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
from . import decks,parse_nextnano as io
from .nextnano_runner import command,discover_parser,parse_check,FATAL
from .artifacts import write_json,manifest,csv
import numpy as np

ROOT=Path(__file__).resolve().parents[1]
PLAN=ROOT/'outputs/28K_extended_8band/work_laptop'


def load_config(path=ROOT/'config/extended_8band.json'):
    c=json.loads(Path(path).read_text())
    if c['k_points']<2 or c['num_electrons']<4 or c['num_holes']<4:raise ValueError('Insufficient points/states')
    if not 0<c['kmax_pi_over_a']<=.2 or c['lattice_constant_nm']<=0:raise ValueError('Invalid acquisition range')
    if c['threads']<1 or c['timeout_seconds']<=0:raise ValueError('Invalid execution settings')
    for f in c['analysis_cutoffs_pi_over_a']+c['presentation_cutoffs_pi_over_a']:
        if not 0<f<=c['kmax_pi_over_a']:raise ValueError('Cutoff outside requested run')
    return c


def render(c):
    n=c['num_electrons']+c['num_holes']
    text=decks.render_kp8({'k_max_per_nm':c['kmax_pi_over_a']*np.pi/c['lattice_constant_nm'],
          'k_points':c['k_points'],'num_electrons':c['num_electrons'],'num_holes':c['num_holes'],
          'output_states':n},'Demo28K finite-k 8-band acquisition; NO single-band anchors')
    text=text.replace('Generated by src/decks.py. Edit config/runner.json, not this file.',
                      'Generated by chi2/extended8band.py. Edit config/extended_8band.json, not this file.')
    text=text.replace('        no_density = yes','        no_density = yes\n        k_point_subdirectories = yes')
    text=text.replace('            k_integration_disabled{}','            lapack{ accuracy = 1e-10 }\n            k_integration_disabled{}')
    text=text.replace('        output_states{',f'        output_energies_on_grid{{ max_num = {n} all_k_points = yes }}\n        output_states{{')
    text=text.replace('            output_masses{ max_num = '+str(n)+' }','')
    problems=decks.static_check(text,'kp8')
    if problems:raise ValueError(problems)
    return text


def prepare(c,parser_exe=None,parser_database=None,no_parse=False,parser_license=None):
    PLAN.mkdir(parents=True,exist_ok=True)
    path=PLAN/'extended_8band.in';path.write_text(render(c),encoding='utf-8')
    write_json(PLAN/'runner.json',c)
    k=np.linspace(0,c['kmax_pi_over_a']*np.pi/c['lattice_constant_nm'],c['k_points'])
    csv(PLAN/'requested_k_grid.csv',np.column_stack([np.arange(len(k)),k,np.zeros(len(k)),k,np.zeros(len(k))]),
        'requested_index,k_per_nm,kx_per_nm,ky_per_nm,kz_per_nm')
    if not parser_exe:parser_exe,parser_database=discover_parser()
    grammar={'status':'NOT_CHECKED','reason':'No configured parser or --no-parse'}
    if not no_parse and parser_exe and parser_database:
        grammar=parse_check(parser_exe,parser_database,path,PLAN/'parser_scratch',parser_license)
    report={'study':'28K_preflight','static_status':'PASS','grammar':grammar,'configuration':c,
        'kmax_per_nm':float(k[-1]),'requested_Nk':len(k),'requested_dk_per_nm':float(k[1]-k[0]),
        'professional_execution_performed':False,'state_count':c['num_electrons']+c['num_holes'],
        'deck_sha256':hashlib.sha256(path.read_bytes()).hexdigest(),
        'output_contract':'24 states and eight complex components at every explicit dispersion k; coverage must be verified after run',
        'grid_distinction':'Only one radial dispersion path; NOT k_integration num_points=1201 (2D grid parameter)',
        'pending':'Professional execution and actual finite-k output coverage; scalar Eq2 optical mapping review'}
    write_json(PLAN/'metadata.json',report)
    print('28K static PASS; grammar '+grammar['status']+'; no Professional solve launched')
    if grammar['status']=='FAIL':
        print('Parser: '+grammar['parser']+'\nErrors: '+'; '.join(grammar['errors']))
        for line in grammar.get('output_tail',[]):print('  | '+line)
    return report


def inventory(root,c,check_hashes=True):
    """Fail closed on old k=0-only archives, wrong grid, missing components or transfer corruption."""
    root=Path(root);problems=[]
    required=['run_configuration.json','run_metadata.json','decks/extended_8band.in','checksums.json','solver.log']
    problems.extend('missing '+p for p in required if not (root/p).is_file())
    raw=root/'raw'
    try:
        k,e,km=io.read_dispersion(raw)
        if len(k)!=c['k_points']:problems.append(f'Nk={len(k)}, expected {c["k_points"]}')
        expected=np.linspace(0,c['kmax_pi_over_a']*np.pi/c['lattice_constant_nm'],c['k_points'])
        if len(k)==len(expected) and not np.allclose(k,expected,atol=5e-10,rtol=0):problems.append('k grid differs from requested path')
        n=c['num_electrons']+c['num_holes']
        if e.shape[1]!=n:problems.append(f'dispersion has {e.shape[1]} states; expected {n}')
        if not np.isfinite(e).all():problems.append('nonfinite dispersion energies')
        if not np.allclose(km['direction'],[0,1,0],atol=1e-7,rtol=0):problems.append('wrong radial direction')
        files=list(raw.rglob('*'));lookup={}
        for p in files:
            if p.is_file():lookup.setdefault(p.name,[]).append(p)
        # Local k suffix is not trusted without energy agreement with explicit dispersion.
        missing_count=0
        for i in range(len(k)):
            for name in [f'energy_spectrum_k{i:05d}.dat',f'spinor_composition_k{i:05d}_CbHhLhSo.dat']:
                matches=lookup.get(name,[])
                if len(matches)!=1:
                    missing_count+=1
                    if missing_count<=8:problems.append(f'{name}: expected one file, found {len(matches)}')
                elif name.startswith('energy'):
                    energy=io.read_energy_spectrum(matches[0])
                    if energy.shape!=(n,) or not np.allclose(energy,e[i],atol=1e-7,rtol=0):problems.append(f'energy/index mismatch at k{i}')
                else:
                    comp=io.read_composition(matches[0]);arr=np.column_stack([comp[tag] for tag in io.KP8_COMPONENTS])
                    if arr.shape!=(n,8) or not np.isfinite(arr).all() or not np.allclose(arr.sum(axis=1),1,atol=2e-5):problems.append(f'invalid composition k{i}')
            for s in range(1,n+1):
                for tag in io.KP8_COMPONENTS:
                    name=f'envelope_k{i:05d}_{s:04d}_{tag}.dat'
                    if len(lookup.get(name,[]))!=1:
                        missing_count+=1
                        if missing_count<=8:problems.append('missing/ambiguous '+name)
        if missing_count:problems.append(f'{missing_count} missing/ambiguous finite-k files total; no k0 fallback')
    except (ValueError,OSError,KeyError) as exc:
        problems.append(str(exc));k=np.array([]);e=np.empty((0,0))
    if (root/'run_metadata.json').exists():
        info=json.loads((root/'run_metadata.json').read_text())
        if not info.get('professional_execution_performed') or info.get('return_code')!=0:problems.append('no successful recorded Professional execution')
    if (root/'run_configuration.json').exists() and json.loads((root/'run_configuration.json').read_text())!=c:problems.append('returned configuration mismatch')
    if check_hashes and (root/'checksums.json').exists():
        rows=json.loads((root/'checksums.json').read_text())
        listed={row['file'] for row in rows}
        actual={p.relative_to(root).as_posix() for p in root.rglob('*') if p.is_file()
                and p.name not in ('checksums.json','return_validation.json')}
        if listed!=actual:problems.append('checksum manifest does not cover exactly the transferred files')
        for row in rows:
            p=(root/row['file']).resolve()
            if not p.is_relative_to(root.resolve()):problems.append('unsafe manifest path');continue
            if not p.is_file() or hashlib.sha256(p.read_bytes()).hexdigest()!=row['sha256']:problems.append('checksum mismatch '+row['file'])
    if (root/'decks/extended_8band.in').exists() and (root/'decks/extended_8band.in').read_text()!=render(c):
        problems.append('returned deck differs from configured deck')
    return {'study':'28K_return_validation','status':'PASS' if not problems else 'FAIL','problems':problems,
            'source':str(root.resolve()),'Nk':len(k),'state_count':e.shape[1],
            'scope':'File coverage, explicit k/energy correspondence, composition and hashes; spinor normalization/operators additionally checked by28L/M',
            'new_physics_analysis_performed':False}


MACHINE_YAML=ROOT.parents[1]/'config/paths.local.yaml'


def machine_paths(args):
    """CLI flag > NEXTNANO_* env > nextnano/config/paths.local.yaml (same file the other demos use)."""
    local={}
    if MACHINE_YAML.is_file():
        import yaml
        block=(yaml.safe_load(MACHINE_YAML.read_text(encoding='utf-8')) or {}).get('nextnano++') or {}
        local={k:os.path.expanduser(os.path.expandvars(str(v))) for k,v in block.items()
               if k in ('exe','database','license') and v and not str(v).startswith('PATH_TO_')}
    pick=lambda flag,env,key:flag or os.environ.get(env) or local.get(key)
    return (pick(args.exe,'NEXTNANO_EXE','exe'),pick(args.database,'NEXTNANO_DATABASE','database'),
            pick(args.license,'NEXTNANO_LICENSE','license'))


def run(c,args):
    exe,db,lic=machine_paths(args)
    for label,p in [('executable',exe),('database',db),('license',lic)]:
        if not p or not Path(p).is_file():raise ValueError('Configure Professional '+label+' via CLI, NEXTNANO_* environment or '+str(MACHINE_YAML)+' (got '+repr(p)+')')
    if 'free' in Path(exe).name.lower():raise ValueError('Professional required; Free executable rejected')
    result=(args.output or ROOT/c['result_directory']).resolve()
    if result.exists():raise ValueError('Refusing existing output directory; choose a new --output')
    # Strict grammar check before any licensed solve.
    prep=prepare(c,exe,db,parser_license=lic)
    if prep['grammar']['status']!='PASS':raise ValueError('Grammar must PASS before --run')
    result.mkdir(parents=True);(result/'decks').mkdir()
    deck=result/'decks/extended_8band.in';deck.write_text(render(c),encoding='utf-8')
    write_json(result/'run_configuration.json',c)
    (result/'requested_k_grid.csv').write_bytes((PLAN/'requested_k_grid.csv').read_bytes())
    argv=command(exe,db,lic,deck,result/'raw',c['threads'])
    info={'study':'28K','started_utc':datetime.now(timezone.utc).isoformat(),'professional_execution_performed':False,
          'argv':argv,'executable_sha256':hashlib.sha256(Path(exe).read_bytes()).hexdigest(),
          'database_sha256':hashlib.sha256(Path(db).read_bytes()).hexdigest(),'grammar_check':prep['grammar'],
          'note':'License contents not copied; exact solver version/header retained in solver.log and simulation_info'}
    write_json(result/'run_metadata.json',info)
    try:
        with (result/'solver.log').open('w',encoding='utf-8') as log:
            info['professional_execution_performed']=True;write_json(result/'run_metadata.json',info)
            done=subprocess.run(argv,cwd=result,stdout=log,stderr=subprocess.STDOUT,timeout=c['timeout_seconds'],check=False)
        info['return_code']=done.returncode
        blob=(result/'solver.log').read_text(errors='replace').lower()
        if any(x in blob for x in FATAL):info['return_code']=info['return_code'] or 1
    except (OSError,subprocess.TimeoutExpired) as exc:info.update(return_code=-1,error=str(exc))
    info['finished_utc']=datetime.now(timezone.utc).isoformat();write_json(result/'run_metadata.json',info)
    write_json(result/'checksums.json',[p for p in manifest(result) if p['file'] not in ['checksums.json','return_validation.json']])
    validation=inventory(result,c);write_json(result/'return_validation.json',validation)
    print('Return-data coverage '+validation['status']+'. Keep the ENTIRE directory: '+str(result))
    return 0 if validation['status']=='PASS' else 2


def main(argv=None):
    p=argparse.ArgumentParser(description=__doc__);m=p.add_mutually_exclusive_group()
    m.add_argument('--run',action='store_true');m.add_argument('--preflight',action='store_true');m.add_argument('--dry-run',action='store_true');m.add_argument('--validate',type=Path)
    p.add_argument('--config',type=Path,default=ROOT/'config/extended_8band.json');p.add_argument('--output',type=Path)
    p.add_argument('--exe');p.add_argument('--database');p.add_argument('--license');p.add_argument('--no-parse',action='store_true')
    a=p.parse_args(argv)
    try:
        c=load_config(a.config)
        if a.validate:
            r=inventory(a.validate,c);print(json.dumps(r,indent=2));return 0 if r['status']=='PASS' else 2
        if a.run:return run(c,a)
        exe,db,lic=machine_paths(a)
        r=prepare(c,exe,db,a.no_parse,lic)
        print('Work command: python scripts/run_extended_8band.py --run')
        return 1 if r['grammar']['status']=='FAIL' else 0
    except (OSError,ValueError,KeyError) as exc:print('ERROR:',exc);return 2
